-- simple-todos 테이블 생성
CREATE TABLE simple_todos
(
    id        INT AUTO_INCREMENT PRIMARY KEY,
    title     VARCHAR(255),
    content   VARCHAR(255),
    status    VARCHAR(50),
    category  VARCHAR(50),
    createdAt TIMESTAMP,
    updatedAt TIMESTAMP,
    deletedAt TIMESTAMP,
    ownerId   INT
);

INSERT INTO simple_todos (title, content, status, category, createdAt, updatedAt, ownerId)
SELECT
    CONCAT('제목 ', FLOOR(1 + (RAND() * 10))) AS title,
    CONCAT('설명 ', FLOOR(1 + (RAND() * 10))) AS content,
    CASE
        WHEN RAND() < 0.25 THEN 'CREATED'
        WHEN RAND() < 0.5 THEN 'IN_PROGRESS'
        WHEN RAND() < 0.75 THEN 'DONE'
        ELSE 'HOLDING'
        END AS status,
    CASE
        WHEN RAND() < 0.33 THEN 'STUDY'
        WHEN RAND() < 0.67 THEN 'WORK_OUT'
        ELSE 'LIFE'
        END AS category,
    NOW() - INTERVAL FLOOR(RAND() * 365) DAY AS createdAt,
    NOW() AS updatedAt,
    FLOOR(1001 + (RAND() * 20)) AS ownerId
FROM
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL
    SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL
    SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
    SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20) AS a
    CROSS JOIN
    (SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL
    SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10 UNION ALL
    SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
    SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL SELECT 20) AS b;

